name: ci

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  pre-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js and Pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0
      - uses: pnpm/action-setup@v
        with:
          version: 9
          
      - name: Install dependencies
        run: bun install
        
      - name: Check transpiler
        run: bun ts:check
        
      - name: Check eslint
        run: bun lint:check

      - name: Check tests
        run: bun run test  